import { ApifyClient } from "apify-client";

interface InstagramPost {
  id?: string;
  shortcode?: string;
  url?: string;

  caption?: string;

  ownerUsername?: string;
  ownerFullName?: string;

  likesCount?: number;
  commentsCount?: number;
  sharesCount?: number;
  videoViewCount?: number;

  displayUrl?: string;
  type?: string;

  timestamp?: string;

  hashtags?: string[];

  latestComments?: Array<{
    id?: string;
    text?: string;
    ownerUsername?: string;
    likesCount?: number;
    timestamp?: string;
  }>;
}

export interface InstagramPostData {
  platform: "INSTAGRAM";

  url: string;

  authorName: string | null;
  authorHandle: string | null;

  content: string | null;

  postType: string;

  likes: number | null;
  comments: number | null;
  shares: number | null;
  views: number | null;

  publishedAt: string | null;

  imageUrl: string | null;

  hashtags: string[];

  latestComments: Array<{
    text: string;
    authorHandle: string | null;
    likes: number;
  }>;

  raw: InstagramPost;
}

/**
 * Make sure the URL is an Instagram post/reel URL.
 */
function validateInstagramUrl(url: string): boolean {
  try {
    const parsed = new URL(url);

    const hostname = parsed.hostname
      .toLowerCase()
      .replace(/^www\./, "");

    if (hostname !== "instagram.com") {
      return false;
    }

    return (
      parsed.pathname.startsWith("/p/") ||
      parsed.pathname.startsWith("/reel/") ||
      parsed.pathname.startsWith("/reels/")
    );
  } catch {
    return false;
  }
}

/**
 * Fetch one public Instagram post using Apify.
 */
export async function fetchInstagramPost(
  url: string
): Promise<InstagramPostData> {
  const apiToken = process.env.APIFY_API_TOKEN;

  if (!apiToken) {
    throw new Error(
      "Apify API is not configured. Please add APIFY_API_TOKEN to .env."
    );
  }

  if (!validateInstagramUrl(url)) {
    throw new Error(
      "Invalid Instagram post URL."
    );
  }

  console.log(
    "Fetching Instagram post through Apify:",
    url
  );

  const client = new ApifyClient({
    token: apiToken,
  });

  /*
   * This is the same Apify Actor you tested
   * successfully from the Apify dashboard.
   */
  const actorId =
    "apify/instagram-scraper";

  try {
    const run = await client
      .actor(actorId)
      .call({
        directUrls: [url],
        resultsType: "posts",
        resultsLimit: 1,
      });

    console.log(
      "Instagram Apify run completed:",
      run.id
    );

    /*
     * Read the dataset generated by the Actor.
     */
    const { items } = await client
      .dataset(run.defaultDatasetId)
      .listItems();

    if (!items || items.length === 0) {
      throw new Error(
        "Instagram post could not be retrieved."
      );
    }

    const post =
      items[0] as InstagramPost;

    console.log(
      "Instagram post retrieved successfully."
    );

    /*
     * Convert Apify's response into the
     * format used by SocialIntel.
     */
    const latestComments =
      Array.isArray(post.latestComments)
        ? post.latestComments
            .slice(0, 20)
            .map((comment) => ({
              text: comment.text ?? "",
              authorHandle:
                comment.ownerUsername ?? null,
              likes:
                comment.likesCount ?? 0,
            }))
        : [];

    const postType =
      typeof post.type === "string"
        ? post.type.toUpperCase()
        : "POST";

    return {
      platform: "INSTAGRAM",

      url:
        post.url ??
        url,

      authorName:
        post.ownerFullName ??
        null,

      authorHandle:
        post.ownerUsername
          ? `@${post.ownerUsername}`
          : null,

      content:
        post.caption ??
        null,

      postType,

      likes:
        typeof post.likesCount === "number"
          ? post.likesCount
          : null,

      comments:
        typeof post.commentsCount === "number"
          ? post.commentsCount
          : null,

      /*
       * Instagram does not reliably expose
       * shares through this scraper.
       */
      shares: null,

      views:
        typeof post.videoViewCount === "number"
          ? post.videoViewCount
          : null,

      publishedAt:
        post.timestamp ??
        null,

      imageUrl:
        post.displayUrl ??
        null,

      hashtags:
        Array.isArray(post.hashtags)
          ? post.hashtags
          : [],

      latestComments,

      raw: post,
    };
  } catch (error) {
    console.error(
      "Instagram Apify error:",
      error
    );

    if (error instanceof Error) {
      throw new Error(
        `Instagram data retrieval failed: ${error.message}`
      );
    }

    throw new Error(
      "Instagram data retrieval failed."
    );
  }
}